const myData = [{
    projectImg: 'images/project1.svg',
    projectTitle: 'Tonic',
    projectDesc: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    modalDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi.',
    technologies: ['html', 'css', 'javaScript'],
    link1: 'https://bizuns.com/symbols-bullets-copy-paste',
    link2: 'https://self-publishingschool.com/how-to-write-dialogue/',
    customStyle: 'row',
    projectQual: ['helo', 'hi', 'bye'],
  },
  {
    projectImg: 'images/portfolio2.svg',
    projectTitle: 'Multi-Post Stories',
    projectDesc: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    modalDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi.',
    technologies: ['html', 'css', 'javaScript'],
    link1: 'https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2238',
    link2: 'https://self-publishingschool.com/how-to-write-dialogue/',
    customStyle: 'row-reverse',
    projectQual: ['helo', 'hi', 'bye'],
  },
  {
    projectImg: 'images/project3.png',
    projectTitle: 'Tonic',
    projectDesc: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    modalDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi.',
    technologies: ['html', 'css', 'javaScript'],
    link1: 'https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2238',
    link2: 'https://self-publishingschool.com/how-to-write-dialogue/',
    customStyle: 'row',
    projectQual: ['helo', 'hi', 'bye'],
  },
  {
    projectImg: 'images/project4.svg',
    projectTitle: 'Multi-Post Stories',
    projectDesc: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    modalDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam architecto sint, quae sit nostrum accusamus magnam blanditiis iusto in ducimus eligendi voluptatibus commodi.',
    technologies: ['html', 'css', 'javaScript'],
    link1: 'https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2238',
    link2: 'https://self-publishingschool.com/how-to-write-dialogue/',
    customStyle: 'row-reverse',
    projectQual: ['helo', 'hi', 'bye'],
  },
  ];

  export { myData as default }